# Generated by Django 3.2 on 2021-04-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_num', models.SmallIntegerField()),
                ('main_contact', models.CharField(default='CLIENT', max_length=200)),
                ('status', models.SmallIntegerField(choices=[(1, 'Not Delivered'), (2, 'Delivered'), (3, 'Failed')], default=1)),
            ],
        ),
    ]
