# Generated by Django 3.2 on 2021-04-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Not delivered'), (2, 'Delivered'), (3, 'Failed')], default=1),
        ),
    ]
