# Generated by Django 3.1.3 on 2021-04-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_auto_20210428_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.CharField(default='Tank', max_length=100),
            preserve_default=False,
        ),
    ]
