# Generated by Django 3.1.3 on 2021-04-28 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_route_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveries.route'),
        ),
    ]
