# Generated by Django 3.1.3 on 2021-04-28 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_delivery_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='driver',
        ),
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
