# Generated by Django 3.1.3 on 2021-04-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_auto_20210428_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.CharField(default='Mike', max_length=255),
        ),
    ]
