# Generated by Django 3.1.3 on 2021-04-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0008_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='token',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
